using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RaSed.Application.DTOs.Realtime
{
    /// <summary>
    /// Threshold-based alert sent to the frontend via SignalR "ReceiveAlert"
    /// Generated by SensorDataProcessor when a sensor value exceeds a threshold.
    /// </summary>
    public class AlertDto
    {
        public string Type { get; set; } = string.Empty;
        public string Message { get; set; } = string.Empty;
        public DateTime Timestamp { get; set; }
        public string Severity { get; set; } = "Info";
    }
}
