using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace RaSed.Domain.Entities
{
   public class FcmDeviceToken
    {
        public int Id { get; set; }

        public int EmployeeId { get; set; }

        public Employee? Employee { get; set; }

        /// <summary>Token generated by FCM on the device. Changes on reinstall.</summary>
        public string Token { get; set; } = null!;

        /// <summary>e.g. "android", "ios" — for future channel config</summary>
        public string Platform { get; set; } = null!;

        public DateTime RegisteredAt { get; set; }
        public DateTime? LastUsedAt { get; set; }
    }
}
